import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`
          ${inter.variable} 
          antialiased
          min-h-[100dvh] 
          w-full 
          overflow-x-hidden !overflow-y-auto
        `}
      >
        {/* FORCE ALWAYS SCROLL TOP AFTER HYDRATION */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.history.scrollRestoration = "manual";
              window.scrollTo(0, 0);
            `,
          }}
        />

        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
