import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers"; // 🔹 নতুন Providers import

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${inter.variable} antialiased`}
      >
        {/* 🔹 এখন react-query provider পুরো অ্যাপকে wrap করবে */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
